//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnsanK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public int Personelİd { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Telno { get; set; }
        public string Tcno { get; set; }
        public int Görev { get; set; }
    
        public virtual tblGörev tblGörev { get; set; }
    }
}
